"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env vive na raiz do projeto (Spreading/), um nível acima de django/
load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Vem do .env em produção. Fallback inseguro só serve para DEBUG/dev local.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or "django-insecure-dev-only-CHANGE-ME-in-.env"

# SECURITY WARNING: don't run with debug turned on in production!
# Default seguro: em produção (Fly injeta FLY_APP_NAME) começa DESLIGADO mesmo se
# alguém esquecer de setar a var; em dev local (sem FLY_APP_NAME) começa ligado.
DEBUG = os.getenv("DJANGO_DEBUG", "0" if os.getenv("FLY_APP_NAME") else "1") == "1"
APP_ENV = os.getenv(
    "APP_ENV", "production" if os.getenv("FLY_APP_NAME") else "development",
).strip().lower()
if APP_ENV not in {"development", "test", "staging", "production"}:
    raise ImproperlyConfigured(
        "APP_ENV deve ser development, test, staging ou production."
    )

if not DEBUG and SECRET_KEY.startswith("django-insecure"):
    raise RuntimeError("Defina DJANGO_SECRET_KEY no .env antes de rodar com DEBUG=0.")

# DEBUG ligado num ambiente que serve gente é falha de configuração, não modo de
# operação: além das páginas de erro com stack e settings, é ele que habilita o
# autologin de superusuário mais abaixo. O default de DEBUG olha FLY_APP_NAME, e
# essa é justamente a variável que some quando a MESMA imagem roda em qualquer
# outro lugar — então a proteção não pode depender só dele. Aqui é fechar a
# porta: staging e produção não sobem com DEBUG, param.
if DEBUG and APP_ENV in {"staging", "production"}:
    raise ImproperlyConfigured(
        f"DEBUG está ligado com APP_ENV={APP_ENV}. "
        "Defina DJANGO_DEBUG=0 ou corrija APP_ENV antes de subir."
    )

# Hosts liberados (CSV no .env). Em dev cai no localhost.
# Default cobre Fly.io (.fly.dev) e túnel do cloudflare (.trycloudflare.com).
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", ".fly.dev,.trycloudflare.com").split(",") if h.strip()]
PUBLIC_BASE_URL = os.getenv(
    "PUBLIC_BASE_URL",
    f"https://{os.getenv('FLY_APP_NAME', 'spreading-web')}.fly.dev",
)
BILLING_CHECKOUT_URL = os.getenv("BILLING_CHECKOUT_URL", "")
BILLING_PORTAL_URL = os.getenv("BILLING_PORTAL_URL", "")
# Cadastro público FECHADO por padrão: o produto é vendido com onboarding
# controlado — o superadmin cria as contas pelo painel (/scrapers/painel-admin/).
# Reabra o self-service só se quiser, com PERMITIR_CADASTRO_PUBLICO=1 no .env.
PERMITIR_CADASTRO_PUBLICO = os.getenv("PERMITIR_CADASTRO_PUBLICO", "0") == "1"
SECURITY_FREEZE_NEW_TENANTS = os.getenv(
    "SECURITY_FREEZE_NEW_TENANTS",
    "1" if APP_ENV in {"staging", "production"} else "0",
) == "1"
# Automação de browser (logins ML/Amazon, Link Builder, relatórios, WhatsApp Web)
# nasce LIGADA em todos os ambientes: são funcionalidades básicas do produto e
# ficar desligada por padrão em produção quebrava login e coletas. Cada recurso
# ainda pode ser desligado pontualmente pela sua env var (kill switch por deploy).
_AUTOMATION_DEFAULT = "1"
ML_BROWSER_LOGIN_ENABLED = os.getenv(
    "ML_BROWSER_LOGIN_ENABLED", _AUTOMATION_DEFAULT,
) == "1"
ML_LINK_BUILDER_ENABLED = os.getenv(
    "ML_LINK_BUILDER_ENABLED", _AUTOMATION_DEFAULT,
) == "1"
ML_BROWSER_REPORTS_ENABLED = os.getenv(
    "ML_BROWSER_REPORTS_ENABLED", _AUTOMATION_DEFAULT,
) == "1"
# A tela de login da Amazon era a única das três sem kill-switch: um problema no
# gateway da Amazon não tinha como ser contido sem deploy.
AMAZON_BROWSER_LOGIN_ENABLED = os.getenv(
    "AMAZON_BROWSER_LOGIN_ENABLED", _AUTOMATION_DEFAULT,
) == "1"
SHOPEE_BROWSER_LOGIN_ENABLED = os.getenv(
    "SHOPEE_BROWSER_LOGIN_ENABLED", _AUTOMATION_DEFAULT,
) == "1"
TELETHON_RELINK_ENABLED = os.getenv(
    "TELETHON_RELINK_ENABLED", "0",
) == "1"
WHATSAPP_WEB_ENABLED = os.getenv(
    "WHATSAPP_WEB_ENABLED", _AUTOMATION_DEFAULT,
) == "1"
# Transporte da verificação de destino do link de afiliado: "browser" (padrão) ou
# "http". O HTTP seria ~1s por link contra ~6s do browser, mas foi MEDIDO como
# inviável: o ML responde `/gz/account-verification` a qualquer cliente sem
# fingerprint de browser (TLS/JA3), tanto do IP de casa quanto do datacenter da Fly.
# Nem User-Agent completo, nem cookies aquecidos pela home contornam. O módulo
# link_http fica pronto e testado caso o ML afrouxe — trocar aqui não exige deploy.
ML_VERIFICACAO_TRANSPORTE = os.getenv("ML_VERIFICACAO_TRANSPORTE", "browser")
# Verificações simultâneas. É I/O puro (o GIL não atrapalha), mas são requisições
# ao ML a partir de um IP de datacenter: subir demais convida rate-limit.
ML_VERIFICACAO_THREADS = int(os.getenv("ML_VERIFICACAO_THREADS", "4"))
# Cupons de ATIVAÇÃO do Mercado Livre (clique no container público, sem código
# digitável). Nasce LIGADA: é funcionalidade básica — sem ela milhares de cupons
# válidos são descartados como "feature_global_kill_switch". Para conter um
# problema sem deploy, desligue com ML_CUPONS_ATIVACAO_ENABLED=0 no ambiente.
ML_CUPONS_ATIVACAO_ENABLED = os.getenv("ML_CUPONS_ATIVACAO_ENABLED", "1") == "1"
ML_COUPON_CODES_ENABLED = os.getenv("ML_COUPON_CODES_ENABLED", "1") == "1"
AMAZON_COUPON_ACTIVATION_ENABLED = (
    os.getenv("AMAZON_COUPON_ACTIVATION_ENABLED", "1") == "1"
)
AMAZON_COUPON_CODES_ENABLED = os.getenv("AMAZON_COUPON_CODES_ENABLED", "1") == "1"
PILOT_ORGANIZATION_IDS = {
    value.strip() for value in os.getenv("PILOT_ORGANIZATION_IDS", "").split(",")
    if value.strip()
}
ML_CUPONS_ATIVACAO_PILOT_ORGANIZATION_IDS = {
    value.strip()
    for value in os.getenv("ML_CUPONS_ATIVACAO_PILOT_ORGANIZATION_IDS", "").split(",")
    if value.strip()
}
COUPON_AFFILIATE_LINK_TTL_HOURS = max(
    1, int(os.getenv("COUPON_AFFILIATE_LINK_TTL_HOURS", "168")),
)
AMAZON_GENERAL_COUPONS_URL = os.getenv("AMAZON_GENERAL_COUPONS_URL", "").strip()
# Meta de cupons distintos PRONTOS por loja (Mercado Livre, Amazon e Shopee), do
# contrato de aceite. Nenhum total agregado compensa uma loja abaixo dela; ver
# apps.scrapers.coupon_abundance.
COUPON_ABUNDANCE_GOAL = int(os.getenv("COUPON_ABUNDANCE_GOAL", "100"))
# Piso do benefício monetário real de um cupom percentual/fixo, em reais. Existe
# porque "50% OFF" com teto de R$1 (desconto_maximo=1.0) é dado real do
# Mercado Livre, não bug de parser — e é lixo: o comprador nunca leva mais que
# R$1, não importa o percentual anunciado. Medido em produção em 03/09/2026
# (cupom Glamour.div: 50% OFF, desconto_maximo=1.0). R$10 é conservador o
# bastante para não vetar categorias legítimas de ticket baixo.
COUPON_VALOR_MINIMO_RELEVANTE_REAIS = float(
    os.getenv("COUPON_VALOR_MINIMO_RELEVANTE_REAIS", "10") or "10"
)
COUPON_DAILY_DISCOVERY_GOAL = int(
    os.getenv("COUPON_DAILY_DISCOVERY_GOAL", "250")
)

# --- Camada Deal (apps.scrapers.deals) ---------------------------------------
# Quanto do preço o cupom precisa abater para o par produto+cupom virar mensagem.
# `COUPON_VALOR_MINIMO_RELEVANTE_REAIS` julga o TETO genérico do cupom; este julga
# o que ele vale NAQUELE item: R$ 20 OFF é ótimo num item de R$ 120 e irrelevante
# num de R$ 4.000. Os dois pisos valem juntos, não alternadamente.
DEAL_BENEFICIO_MINIMO_PERCENT = float(
    os.getenv("DEAL_BENEFICIO_MINIMO_PERCENT", "5") or "5"
)
# Quantos deals elegíveis por dia uma regra precisa ter para a cobertura passar.
# Folga deliberada sobre os 3–10 publicáveis: cooldown, revalidação e falha de
# link consomem candidatos entre a seleção e o envio.
DEAL_COBERTURA_META_DIA = int(os.getenv("DEAL_COBERTURA_META_DIA", "10"))
# Idade máxima da observação de preço que um deal aceita, em minutos. O catálogo
# considera um produto "fresco" por 48 h — folga correta para EXIBIR, folga
# absurda para AFIRMAR. Medido em 03/09/2026: a air fryer publicada tinha 1021
# minutos de observação, a vitrine dizia R$ 199,90 e o checkout cobrava R$ 249,50.
# Com ~270 produtos ML relidos por hora, 90 minutos deixa estoque de sobra.
DEAL_FRESCOR_MAXIMO_MIN = int(os.getenv("DEAL_FRESCOR_MAXIMO_MIN", "90"))
# Quantas páginas da vitrine `/ofertas` a verificação de envio varre atrás do
# card do item. É a única porta que este IP tem aberta no ML; cada página custa
# um carregamento, então o teto existe para o envio não virar raspagem.
PRECO_JIT_PAGINAS_OFERTAS = int(os.getenv("PRECO_JIT_PAGINAS_OFERTAS", "4"))
# Ritmo do número de WhatsApp. A detecção de automação é heurística e o sinal mais
# forte é cadência: rajada do mesmo número em poucos segundos. O jitter por regra
# (`ConfiguracaoEnvio.agendar_proximo`) deixa cada regra irregular, mas dez regras
# vencendo no mesmo tique disparavam em sequência — que é o padrão de robô.
#
# A orientação pública para número não aquecido fica abaixo de 30 mensagens por
# hora; 20 é conservador. O teto por tique existe para o pico de oferta relâmpago
# não virar rajada: com tique de 5 min, dois por tique já dão 24/hora de teoria,
# e o teto horário segura o resto.
WHATSAPP_ENVIOS_POR_TICK = int(os.getenv("WHATSAPP_ENVIOS_POR_TICK", "2"))
WHATSAPP_ENVIOS_POR_HORA = int(os.getenv("WHATSAPP_ENVIOS_POR_HORA", "20"))
# Espaçamento entre dois envios do mesmo número dentro de um tique, com variação
# aleatória: intervalo constante é tão denunciável quanto a rajada.
WHATSAPP_ESPACO_MIN_S = int(os.getenv("WHATSAPP_ESPACO_MIN_S", "20"))
WHATSAPP_ESPACO_MAX_S = int(os.getenv("WHATSAPP_ESPACO_MAX_S", "60"))
# Shadow calcula o vencedor da camada Deal e registra a divergência SEM trocar o
# envio. Live é o que troca, e nasce desligado: o rollback é apagar a flag, não
# reverter migração.
DEAL_LAYER_SHADOW = os.getenv("DEAL_LAYER_SHADOW", "1") == "1"
DEAL_LAYER_LIVE = os.getenv("DEAL_LAYER_LIVE", "0") == "1"
# Allowlist PRÓPRIA do recurso. Sem ela, `enabled_for_user` cairia na lista geral
# `PILOT_ORGANIZATION_IDS` e ligar a camada para uma conta de teste a ligaria para
# todas as organizações do piloto de envio — que é exatamente o acidente que a
# separação por recurso existe para impedir.
DEAL_LAYER_LIVE_PILOT_ORGANIZATION_IDS = {
    value.strip()
    for value in os.getenv("DEAL_LAYER_LIVE_PILOT_ORGANIZATION_IDS", "").split(",")
    if value.strip()
}
# Mantida como registro de uma ideia que se provou errada: quando a camada está
# ligada, não existe "cai para o caminho antigo". O legado publica sem medir preço
# no envio, então usá-lo como rede de segurança devolvia exatamente a mentira que a
# camada existe para impedir. Sem deal, não se publica.
DEAL_FALLBACK_CUPOM_SOLTO = False
# Portais autenticados reais, ainda sobrescrevíveis caso as lojas mudem a rota.
# Sem sessão ambos redirecionam ao login, que o adapter classifica como ação do
# usuário; uma instalação nova não deve nascer incapaz de medir conversão.
ML_AFFILIATE_REPORT_URL = os.getenv(
    "ML_AFFILIATE_REPORT_URL",
    "https://www.mercadolivre.com.br/afiliados/dashboard",
)
AMAZON_ASSOCIATES_REPORT_URL = os.getenv(
    "AMAZON_ASSOCIATES_REPORT_URL",
    "https://associados.amazon.com.br/home/reports",
)
AMAZON_BROWSER_REPORTS_ENABLED = os.getenv(
    "AMAZON_BROWSER_REPORTS_ENABLED", "1",
) == "1"
AMAZON_COUPON_MAX_PAGES = int(os.getenv("AMAZON_COUPON_MAX_PAGES", "5"))
AMAZON_COUPON_MAX_ITEMS = int(os.getenv("AMAZON_COUPON_MAX_ITEMS", "500"))
AMAZON_COUPON_MAX_SECONDS = int(os.getenv("AMAZON_COUPON_MAX_SECONDS", "180"))
CHROMIUM_GLOBAL_SLOTS = int(os.getenv("CHROMIUM_GLOBAL_SLOTS", "1"))
MANUAL_QUEUE_NO_WORKER_TIMEOUT_SECONDS = int(os.getenv(
    "MANUAL_QUEUE_NO_WORKER_TIMEOUT_SECONDS", "600",
))
MANUAL_QUEUE_MAX_WAIT_SECONDS = int(os.getenv("MANUAL_QUEUE_MAX_WAIT_SECONDS", "2700"))
SEND_PIPELINE_V2_ENABLED = os.getenv("SEND_PIPELINE_V2_ENABLED", "0") == "1"
SEND_RETRY_BASE_SECONDS = int(os.getenv("SEND_RETRY_BASE_SECONDS", "30"))
SEND_RETRY_MAX_SECONDS = int(os.getenv("SEND_RETRY_MAX_SECONDS", "900"))
SEND_MAX_ATTEMPTS = int(os.getenv("SEND_MAX_ATTEMPTS", "5"))
WA_SESSION_RECONCILE_SECONDS = int(os.getenv("WA_SESSION_RECONCILE_SECONDS", "60"))
SCRAPER_DIAGNOSTIC_RETENTION_DAYS = int(os.getenv(
    "SCRAPER_DIAGNOSTIC_RETENTION_DAYS", "7",
))
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".fly.dev", ".trycloudflare.com"]
elif DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]
# Fly injeta o hostname do app; libera automaticamente sem precisar configurar.
_fly_app = os.getenv("FLY_APP_NAME", "")
if _fly_app:
    ALLOWED_HOSTS.append(f"{_fly_app}.fly.dev")

# Origens confiáveis para CSRF (precisa de esquema: https://app.seudominio.com).
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS", "https://*.fly.dev,https://*.trycloudflare.com").split(",") if o.strip()]
if _fly_app:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_fly_app}.fly.dev")


# Application definition

INSTALLED_APPS = [
    'apps.scrapers',
    'apps.accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serve os static (admin/etc) direto do processo, sem CDN/nginx.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Precisa envolver Session/Auth: falha do Postgres vira 503 controlado, não 500.
    'core.middleware.DatabaseUnavailableMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    # Tranca usuário logado mas com e-mail não verificado (multi-tenant SaaS).
    'apps.accounts.middleware.EmailVerificadoMiddleware',
    # Barra conta suspensa pelo superadmin.
    'apps.accounts.middleware.ContaBloqueadaMiddleware',
]

# CSP em modo report-only começa desligado. Para testar sem quebrar nada:
# DJANGO_CSP_REPORT_ONLY=1 no .env -> navegador só reporta, não bloqueia.
CSP_REPORT_ONLY = os.getenv("DJANGO_CSP_REPORT_ONLY", "0") == "1"

# Tranca TODO o site por padrão (inclusive em DEBUG). Views públicas marcam
# @login_not_required (login/signup/reset/verificação). Anônimo cai no login.
MIDDLEWARE.insert(
    MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
)
MIDDLEWARE.insert(
    MIDDLEWARE.index('django.contrib.auth.middleware.LoginRequiredMiddleware') + 1,
    'apps.accounts.organization_middleware.OrganizationContextMiddleware',
)

# DEV: auto-login local (dispensa a tela de login). Roda ANTES do LoginRequired
# para já entregar um request.user autenticado.
#
# Exige DEBUG **e** um APP_ENV de desenvolvimento. Só DEBUG não bastava: ele
# nasce ligado sempre que FLY_APP_NAME não existe, que é o caso de qualquer host
# fora da Fly rodando esta mesma imagem — e este middleware cria e autentica um
# SUPERUSUÁRIO para requisição anônima. Duas condições independentes têm de estar
# erradas ao mesmo tempo para o painel abrir sozinho.
if (DEBUG and APP_ENV in {"development", "test"}
        and os.getenv("DEV_AUTOLOGIN", "1") != "0"):
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.contrib.auth.middleware.LoginRequiredMiddleware'),
        'core.middleware.DevAutoLoginMiddleware',
    )

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'apps' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Produção (Fly.io): defina DATABASE_URL (postgres://...). Dev local cai no SQLite.
import dj_database_url  # noqa: E402

_RUNTIME_DATABASE_URL = os.getenv("DATABASE_URL", "")
_MIGRATION_DATABASE_URL = os.getenv("MIGRATION_DATABASE_URL", "")
_SYSTEM_DATABASE_URL = os.getenv("SYSTEM_DATABASE_URL", "")
MIGRATION_DATABASE_CONFIGURED = bool(_MIGRATION_DATABASE_URL)
SYSTEM_DATABASE_CONFIGURED = bool(_SYSTEM_DATABASE_URL)
TENANT_SYSTEM_PROCESS = os.getenv("TENANT_SYSTEM_PROCESS", "0") == "1"
RELEASE_COMMAND_PROCESS = os.getenv("RELEASE_COMMAND") == "1"
TENANT_RUNTIME_DB_ROLE = os.getenv("TENANT_RUNTIME_DB_ROLE", "spreading_runtime")
TENANT_SYSTEM_DB_ROLE = os.getenv("TENANT_SYSTEM_DB_ROLE", "spreading_system")
TENANT_MIGRATION_DB_ROLE = os.getenv(
    "TENANT_MIGRATION_DB_ROLE", "spreading_migration",
)
TENANT_CONTEXT_SIGNING_KEY = os.getenv("TENANT_CONTEXT_SIGNING_KEY", "")
PHASE0_EXPAND_ONLY = os.getenv("PHASE0_EXPAND_ONLY", "0") == "1"
# O release command pode usar uma role dona das tabelas para DDL. As máquinas da
# aplicação continuam usando exclusivamente DATABASE_URL, com uma role sem
# SUPERUSER/BYPASSRLS e sem ownership.
_DATABASE_URL = (
    _MIGRATION_DATABASE_URL
    if RELEASE_COMMAND_PROCESS and _MIGRATION_DATABASE_URL
    else (
        _SYSTEM_DATABASE_URL
        if TENANT_SYSTEM_PROCESS and _SYSTEM_DATABASE_URL
        else _RUNTIME_DATABASE_URL
    )
)
if (
    APP_ENV in {"staging", "production"}
    and RELEASE_COMMAND_PROCESS
    and not _MIGRATION_DATABASE_URL
):
    raise ImproperlyConfigured(
        "MIGRATION_DATABASE_URL é obrigatória no release command."
    )
if (
    APP_ENV in {"staging", "production"}
    and TENANT_SYSTEM_PROCESS
    and not _SYSTEM_DATABASE_URL
):
    raise ImproperlyConfigured(
        "SYSTEM_DATABASE_URL é obrigatória nos workers cross-tenant."
    )
if _DATABASE_URL:
    import dj_database_url
    # ssl_require=False: o Postgres interno do Fly (.flycast/.internal) NÃO usa TLS;
    # forçar sslmode=require quebraria a conexão. Provedores externos (Supabase) já
    # trazem sslmode na própria URL. Sobrescreva com DB_SSL_REQUIRE=1 se precisar.
    DATABASES = {
        "default": dj_database_url.parse(
            _DATABASE_URL, conn_max_age=600,
            ssl_require=os.getenv("DB_SSL_REQUIRE", "0") == "1",
        )
    }
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    # Falha do proxy/VM não pode manter uma request (especialmente /healthz) presa
    # no timeout TCP do sistema. O valor também protege reconexões dos workers.
    if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
        DATABASES["default"].setdefault("OPTIONS", {}).setdefault(
            "connect_timeout", 3,
        )
        if not RELEASE_COMMAND_PROCESS:
            # Um lock preso (transação abandonada segurando a linha da sessão ML)
            # não pode travar uma request até o proxy desistir: erro em 15s e só
            # aquela operação falha, em vez de as 8 threads do gunicorn ficarem
            # presas numa fila de lock — foi o que tirou o site do ar por ~30min.
            # idle_in_transaction mata a sessão que esqueceu o COMMIT (a mesma que
            # segurava aquele lock). O release command (migrate) fica DE FORA: DDL
            # pode esperar um lock legítimo do tráfego ao vivo e backfills longos
            # passariam do statement_timeout.
            DATABASES["default"]["OPTIONS"].setdefault(
                "options",
                "-c lock_timeout=15000 -c statement_timeout=120000 "
                "-c idle_in_transaction_session_timeout=300000",
            )
    if (
        APP_ENV in {"staging", "production"}
        and DATABASES["default"].get("ENGINE") != "django.db.backends.postgresql"
    ):
        raise ImproperlyConfigured(
            f"{APP_ENV} exige PostgreSQL; DATABASE_URL configurou outro backend."
        )
else:
    if APP_ENV in {"staging", "production"}:
        raise ImproperlyConfigured(
            f"DATABASE_URL é obrigatória em {APP_ENV}; SQLite não é permitido."
        )
    # Sem DATABASE_URL cai no SQLite. Em prod (Fly) fica no volume /data (se montado)
    # para sobreviver a deploys; em dev fica ao lado do projeto.
    _sqlite_dir = Path("/data") if Path("/data").is_dir() else BASE_DIR
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _sqlite_dir / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic destino em produção (servido pelo WhiteNoise com hash + gzip).
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Manifest+compressão só em produção. Em DEBUG usa o storage simples (senão o
# {% static %} exigiria manifesto/collectstatic e quebraria o dev).
_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": _staticfiles_backend},
}


# ─────────────────────────────────────────────────────────────
# WhatsApp sender (serviço Node em node.js/index.js)
# ─────────────────────────────────────────────────────────────
WHATSAPP_API_URL = os.getenv("WHATSAPP_API_URL", "http://localhost:3000")
WA_CAPABILITY_PRIVATE_KEY = os.getenv("WA_CAPABILITY_PRIVATE_KEY", "")
WA_CAPABILITY_KEY_ID = os.getenv("WA_CAPABILITY_KEY_ID", "wa-ed25519-v1")
WA_CAPABILITY_ISSUER = os.getenv("WA_CAPABILITY_ISSUER", "spreading-web")
WA_CAPABILITY_AUDIENCE = os.getenv("WA_CAPABILITY_AUDIENCE", "spreading-wa")
WA_CAPABILITY_TTL_SECONDS = min(
    60, max(10, int(os.getenv("WA_CAPABILITY_TTL_SECONDS", "45")))
)


# ─────────────────────────────────────────────────────────────
# Telegram sender (Bot API). Cada usuário conecta o próprio bot pela web
# (Conexão Telegram -> token salvo no Perfil). Este valor é só o FALLBACK global
# usado quando o usuário não tem token próprio (single-tenant/compat).
# ─────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")


# ─────────────────────────────────────────────────────────────
# Afiliado — tag/ID que DEVE aparecer no link final (verificação A3).
# Sem ela, o link não gera comissão. Pegue inspecionando um link real do
# Link Builder (param matt_word/matt_tool/tracking_id na URL de destino).
# ─────────────────────────────────────────────────────────────
AFILIADO_TAG = os.getenv("AFILIADO_TAG", "")
# Recusar envio quando o link não carrega a tag? (1=recusa, 0=envia c/ aviso)
AFILIADO_EXIGIR = os.getenv("AFILIADO_EXIGIR", "1") == "1"

# Conferir o preço ao vivo logo antes de publicar. O catálogo tolera até 48h de
# idade (expire_stale), e era essa janela que fazia a mensagem anunciar um valor
# diferente do que a página cobra. Desligável por secret, sem deploy.
PRECO_REVALIDA_ANTES_ENVIO = os.getenv("PRECO_REVALIDA_ANTES_ENVIO", "1") == "1"
# Fallback por raspagem da PDP quando a Creators API não responde. É Playwright:
# custa segundos e uma das threads do gunicorn, por isso nasce desligado.
PRECO_REVALIDA_PLAYWRIGHT = os.getenv("PRECO_REVALIDA_PLAYWRIGHT", "0") == "1"
# Flag PRÓPRIA do Mercado Livre, separada da Amazon de propósito: o ML depende do
# anti-bot deixar passar o GET autenticado. Se ele apertar, desliga só o ML sem
# levar junto a revalidação da Amazon, que não depende disso.
PRECO_REVALIDA_ML = os.getenv("PRECO_REVALIDA_ML", "1") == "1"
# Teto de tempo para revalidar a colagem inteira de um cupom (até 9 itens em
# paralelo). Estourar o orçamento nunca reprova: o que não voltou fica inconclusivo.
PRECO_REVALIDA_ORCAMENTO_S = float(os.getenv("PRECO_REVALIDA_ORCAMENTO_S", "6"))


# ─────────────────────────────────────────────────────────────
# Amazon — Associates (BR) + Creators API (sucessor da PA-API 5.0, desligada
# em 2026-05-15). Auth OAuth2: Credential ID/Secret -> token bearer (~1h).
# Pegue as credenciais em Associates Central > Tools > Creators API.
# AMAZON_PARTNER_TAG: sua tag de afiliado (ex 'meusite-20') — vai no ?tag= do link.
# ─────────────────────────────────────────────────────────────
AMAZON_PARTNER_TAG = os.getenv("AMAZON_PARTNER_TAG", "")
AMAZON_CREATOR_CREDENTIAL_ID = os.getenv("AMAZON_CREATOR_CREDENTIAL_ID", "")
AMAZON_CREATOR_CREDENTIAL_SECRET = os.getenv("AMAZON_CREATOR_CREDENTIAL_SECRET", "")
# Host do endpoint da Creators API (sem https://). Confirmar na doc autenticada.
AMAZON_CREATORS_HOST = os.getenv("AMAZON_CREATORS_HOST", "")
# Host do marketplace BR usado para montar o link canônico /dp/{ASIN}.
AMAZON_MARKETPLACE = os.getenv("AMAZON_MARKETPLACE", "www.amazon.com.br")
# Desconto mínimo (%) para um item entrar no feed de ofertas Amazon.
AMAZON_MIN_SAVINGS_PCT = float(os.getenv("AMAZON_MIN_SAVINGS_PCT", "15"))
# Páginas de busca varridas por keyword. A Creators API devolve no máximo 10 itens por
# página, então este número multiplica o teto do feed (5 -> até 50 itens por keyword).
# Cada página é uma chamada com throttle de ~1 TPS: subir muito alonga o ciclo.
AMAZON_FEED_PAGES = int(os.getenv("AMAZON_FEED_PAGES", "5"))
AMAZON_PUBLIC_FALLBACK = os.getenv("AMAZON_PUBLIC_FALLBACK", "1") == "1"
AMAZON_PUBLIC_TERMS_PER_CYCLE = max(
    1, int(os.getenv("AMAZON_PUBLIC_TERMS_PER_CYCLE", "4")),
)
AMAZON_PUBLIC_COUPON_TERMS = [
    k.strip() for k in os.getenv(
        "AMAZON_PUBLIC_COUPON_TERMS",
        "brinquedos,eletronicos,livros,beleza,casa,informatica,bebe,games,"
        "ferramentas,cozinha,esportes,automotivo,pet shop,suplementos,vitaminas,"
        "higiene,limpeza,lavanderia,decoracao,jardinagem,papelaria,escritorio,"
        "celular,acessorios para celular,audio,fones de ouvido,climatizacao,"
        "iluminacao,organizacao,cama mesa banho,moda feminina,moda masculina,"
        "bolsas,construcao,bebidas,maquiagem,cuidados pessoais",
    ).split(",") if k.strip()
]
# A busca oficial concentra mais cupons do que a central de ofertas. As 37 categorias
# foram medidas na busca BR em 2026-09. Quatro termos rotativos por ciclo mantêm o
# Chromium dentro da capacidade atual e percorrem o conjunto em no máximo dez
# coletas; páginas posteriores reutilizam a sessão e não baixam mídia.
AMAZON_PUBLIC_PAGES_PER_TERM = max(
    1, int(os.getenv("AMAZON_PUBLIC_PAGES_PER_TERM", "3")),
)
# Saída opcional dedicada para páginas públicas da Amazon. O Fly recebe HTTP 503
# da busca mesmo em regiões diferentes; credenciais ficam somente em secrets.
AMAZON_PUBLIC_PROXY_SERVER = os.getenv("AMAZON_PUBLIC_PROXY_SERVER", "").strip()
AMAZON_PUBLIC_PROXY_USERNAME = os.getenv("AMAZON_PUBLIC_PROXY_USERNAME", "").strip()
AMAZON_PUBLIC_PROXY_PASSWORD = os.getenv("AMAZON_PUBLIC_PROXY_PASSWORD", "").strip()
# A mesma saída residencial PAYG pode atender Shopee e Amazon. Variáveis próprias
# permitem separar provedores mais tarde; sem elas, reaproveitamos o proxy público
# da Amazon para não duplicar mensalidade nem configuração.
SHOPEE_PUBLIC_PROXY_SERVER = os.getenv(
    "SHOPEE_PUBLIC_PROXY_SERVER", AMAZON_PUBLIC_PROXY_SERVER,
).strip()
SHOPEE_PUBLIC_PROXY_USERNAME = os.getenv(
    "SHOPEE_PUBLIC_PROXY_USERNAME", AMAZON_PUBLIC_PROXY_USERNAME,
).strip()
SHOPEE_PUBLIC_PROXY_PASSWORD = os.getenv(
    "SHOPEE_PUBLIC_PROXY_PASSWORD", AMAZON_PUBLIC_PROXY_PASSWORD,
).strip()
AFFILIATE_FEED_URL = os.getenv("AFFILIATE_FEED_URL", "")
AFFILIATE_FEED_TOKEN = os.getenv("AFFILIATE_FEED_TOKEN", "")
AWIN_INTEGRATION_ENABLED = os.getenv("AWIN_INTEGRATION_ENABLED", "1") == "1"
# Shopee: ligada por padrão porque não consome navegador nem custa infraestrutura —
# uma organização sem credencial conectada simplesmente não coleta nada. Os valores
# abaixo são o fallback de desenvolvimento; em produção cada organização assina com
# a própria credencial, guardada cifrada em IntegracaoAfiliado.
SHOPEE_INTEGRATION_ENABLED = os.getenv("SHOPEE_INTEGRATION_ENABLED", "1") == "1"
SHOPEE_APP_ID = os.getenv("SHOPEE_APP_ID", "")
SHOPEE_APP_SECRET = os.getenv("SHOPEE_APP_SECRET", "")
# Palavras-chave de categorias amplas que alimentam o "feed" de ofertas Amazon
# (a Creators API não expõe um feed de ofertas; varremos buscas com min savings).
AMAZON_FEED_KEYWORDS = [
    k.strip() for k in os.getenv(
        "AMAZON_FEED_KEYWORDS",
        "echo dot,fone bluetooth,smart tv,notebook,air fryer,smartwatch,"
        "aspirador robo,monitor,ssd,cafeteira,perfume,tenis",
    ).split(",") if k.strip()
]


# ─────────────────────────────────────────────────────────────
# Monitor de canais curados (Telethon / userbot MTProto) — Track B4.
# Uma CONTA de usuário do Telegram entra nos canais-fonte e lê as mensagens (bots
# não leem canais que não administram). Gere a StringSession uma vez e guarde como
# Fly secret. api_id/api_hash em https://my.telegram.org.
# ─────────────────────────────────────────────────────────────
TELEGRAM_API_ID = int(os.getenv("TELEGRAM_API_ID", "0") or "0")
TELEGRAM_API_HASH = os.getenv("TELEGRAM_API_HASH", "")
TELEGRAM_SESSION = os.getenv("TELEGRAM_SESSION", "")  # StringSession do userbot


# ─────────────────────────────────────────────────────────────
# LLM — resuminho engraçado das ofertas (API do Claude / Anthropic)
# Trocado do Ollama local (não roda no Fly) para a API do Claude. Gate por
# LLM_ATIVO + ANTHROPIC_API_KEY (setar nos secrets do Fly). Sem key => sem frase.
# ─────────────────────────────────────────────────────────────
LLM_ATIVO = os.getenv("LLM_ATIVO", "1") == "1"
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
# Haiku é o padrão. Os call sites em llm.py e cupom_extractor.py já declaravam
# Haiku como _MODELO_PADRAO, mas todos leem getattr(settings, "LLM_MODELO", ...)
# e esta linha SEMPRE define a setting — então o default deles nunca era usado e
# cada chamada saía em Sonnet. A variável continua permitindo fixar outro
# snapshot sem alterar código, quando houver motivo medido.
LLM_MODELO = os.getenv("LLM_MODELO", "claude-haiku-4-5-20251001")
# Preço por milhão de tokens, em dólar (entrada, saída). A chave casa por
# substring do nome do modelo. Contar token é exato; converter para dinheiro é
# uma tabela que envelhece — por isso ela mora aqui, visível, e não no código.
LLM_PRECOS_USD_MTOK = {
    "haiku": (1.0, 5.0),
    "sonnet": (3.0, 15.0),
    "opus": (5.0, 25.0),
}
LLM_CAMBIO_BRL = float(os.getenv("LLM_CAMBIO_BRL", "5.12"))
# Teto mensal de gasto de IA, em reais. Zero desliga o alerta. NÃO bloqueia
# chamada: a decisão registrada foi contador com aviso, não interruptor — um
# corte automático no meio do mês deixaria o funil sem leitura de cupom sem que
# ninguém tivesse escolhido isso.
LLM_TETO_BRL_MES = float(os.getenv("LLM_TETO_BRL_MES", "74"))


# ─────────────────────────────────────────────────────────────
# Redis (Celery broker/backend + cache). Em prod: um REDIS_URL só (ex: Upstash
# no Fly). CELERY_BROKER_URL/RESULT_BACKEND ainda sobrescrevem se você quiser
# separar. Em dev sem Redis, cai em localhost (Celery) e cache local (abaixo).
# ─────────────────────────────────────────────────────────────
REDIS_URL = os.getenv("REDIS_URL", "")
_redis_default = REDIS_URL or "redis://localhost:6379/0"
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", _redis_default)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", _redis_default)
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True


# ─────────────────────────────────────────────────────────────
# Cache — POR PROCESSO, e isso é deliberado.
#
# Quem usa: a fase do login web do ML, o throttle de login e o status do WhatsApp.
# Os dois primeiros só existem dentro do processo web, que roda com --workers 1
# (ver Procfile: a thread do Chromium e a fila de input vivem em dicts em memória
# desse processo). Com um processo só, LocMem é compartilhado entre as 8 threads e
# resolve tudo isso sem tocar em rede nem no banco — e o loop do login lê o cache
# várias vezes por segundo, então DatabaseCache viraria dezenas de queries/s.
#
# Havia aqui um bloco que ligava DatabaseCache quando existia DATABASE_URL; ele era
# sobrescrito incondicionalmente por este e nunca teve efeito (o createcachetable do
# fly.toml criava uma tabela que ninguém usava). Removido: o comportamento real é
# este, e o comentário agora bate com ele.
#
# ATENÇÃO: `--workers 1` e este cache andam juntos. Subir para 2+ workers exige
# mover o estado do ml_conexao (e este cache) para Redis ANTES — senão o login do
# ML quebra de um jeito difícil de achar, e o throttle de login deixa de contar
# tentativas direito.
# ─────────────────────────────────────────────────────────────
_REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL") or os.getenv("REDIS_URL") or (
    CELERY_BROKER_URL if os.getenv("USE_REDIS_CACHE", "0") == "1" else ""
)
if _REDIS_CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_CACHE_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "spreading-local",
        }
    }

# Cache que PRECISA sobreviver a restart. O `default` é LocMem em produção (não há
# Redis), ou seja: morre a cada deploy e no desligamento noturno das 00:00, e nem é
# compartilhado entre os processos do honcho. Para um cache de conveniência isso é
# irrelevante; para o cache do `cupom_extractor` é dinheiro — a leitura de cada
# mensagem de canal é uma chamada paga ao modelo, e o cache de 30 dias existe
# exatamente para não pagar duas vezes pelo mesmo texto. Com LocMem, "30 dias" na
# prática era "até o próximo restart".
#
# Postgres, não Redis: o banco já existe e não acrescenta um centavo à fatura.
# Tabela criada por migração, portanto herda as DEFAULT PRIVILEGES de
# `spreading_migration` (arwd para runtime e system).
CACHES["persistente"] = CACHES["default"] if _REDIS_CACHE_URL else {
    "BACKEND": "django.core.cache.backends.db.DatabaseCache",
    "LOCATION": "spreading_cache",
    "TIMEOUT": None,
    "OPTIONS": {"MAX_ENTRIES": 50000, "CULL_FREQUENCY": 4},
}


# ─────────────────────────────────────────────────────────────
# Autenticação — rotas de redirect
# ─────────────────────────────────────────────────────────────
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

# PBKDF2 (default do Django, ~1M iterações) é seguro. Se argon2-cffi estiver
# instalado, usa Argon2 (mais resistente a GPU). Só prepende se importável —
# evita quebrar login/signup quando a lib não está instalada.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]
try:
    import argon2  # noqa: F401
    PASSWORD_HASHERS.insert(0, "django.contrib.auth.hashers.Argon2PasswordHasher")
except ImportError:
    pass


# ─────────────────────────────────────────────────────────────
# Cookies de sessão / CSRF
# ─────────────────────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY = True          # JS não lê o cookie de sessão
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 dias
# False: a sessão é gravada no banco, então True dava um UPDATE em django_session a
# CADA request — inclusive nos polls de status, que não trazem nada de novo. Com
# SESSION_COOKIE_AGE de 14 dias a expiração deslizante não vale esse custo.
SESSION_SAVE_EVERY_REQUEST = False


# ─────────────────────────────────────────────────────────────
# Hardening — ligado só fora do DEBUG (produção atrás de HTTPS)
# ─────────────────────────────────────────────────────────────
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Atrás de proxy/load balancer que termina TLS:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# E-mail — em dev imprime no console; em prod (ou EMAIL_FORCE_SMTP=1) usa SMTP.
# Titan (HostGator): EMAIL_HOST=smtp.titan.email, EMAIL_PORT=465, EMAIL_USE_SSL=1
# (alternativa: porta 587 com EMAIL_USE_TLS=1). SSL e TLS são mutuamente exclusivos.
EMAIL_FORCE_SMTP = os.getenv("EMAIL_FORCE_SMTP", "0") == "1"
if DEBUG and not EMAIL_FORCE_SMTP:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.titan.email")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "1") == "1"
    # TLS só quando SSL desligado (porta 587). Django proíbe os dois juntos.
    EMAIL_USE_TLS = (not EMAIL_USE_SSL) and os.getenv("EMAIL_USE_TLS", "0") == "1"
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@spreading.app")

# Cooldown (horas) entre alertas repetidos de conexão caída p/ não floodar e-mail.
ALERTA_CONEXAO_COOLDOWN_H = int(os.getenv("ALERTA_CONEXAO_COOLDOWN_H", "6"))
# Canal de operação: para onde vai um incidente `error` quando ele ABRE. Sem isto o
# problema espera alguém abrir a tela de Saúde — o modo de falha de 16, 17 e 18/08.
# ALERTA_TELEGRAM_CHAT_ID usa o TELEGRAM_BOT_TOKEN que já existe; ALERTA_EMAILS é
# lista separada por vírgula. Vazio nos dois = canal desligado (padrão em dev).
# Leitura de cupom em canal por IA. Cada mensagem é lida uma vez (cache por hash)
# e só mensagem com sinal de cupom é enviada — o custo é de leitura, não de volume.
CUPOM_LLM_ATIVO = os.getenv("CUPOM_LLM_ATIVO", "1") == "1"
ALERTA_TELEGRAM_CHAT_ID = os.getenv("ALERTA_TELEGRAM_CHAT_ID", "")
ALERTA_EMAILS = os.getenv("ALERTA_EMAILS", "")
# Silêncio por chave de incidente. Alerta que toca demais é alerta que se ignora.
ALERTA_SILENCIO_MIN = int(os.getenv("ALERTA_SILENCIO_MIN", "60"))
# (ML_AUTH_STALE_DIAS saiu: a idade do arquivo deixou de ser critério de sessão viva
# quando conexoes.py passou a perguntar ao próprio ML, e o único leitor da variável
# já era código morto.)

# ─────────────────────────────────────────────────────────────
# Sessões do ML (auth.json / auth_{id}.json). Precisa ser PERSISTENTE: no Fly o
# filesystem da imagem é efêmero (some a cada deploy). Default: volume /data se
# existir (produção), senão a pasta do scraper (dev). Override: ML_AUTH_DIR.
# ─────────────────────────────────────────────────────────────
_ml_auth_default = "/data/ml_sessions" if Path("/data").is_dir() else str(
    BASE_DIR / "apps" / "scrapers" / "scraper_mercadolivre")
ML_AUTH_DIR = os.getenv("ML_AUTH_DIR", _ml_auth_default)
os.makedirs(ML_AUTH_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────
# Login web do Mercado Livre: o servidor é headless, então o login roda num Chromium
# LOCAL (o mesmo da imagem/Playwright) e a tela é transmitida pro navegador do usuário
# via CDP screencast (ver apps/scrapers/ml_conexao.py). Não precisa de serviço externo
# nem de chaves — substituiu o antigo Browserbase (browser hospedado pago).
# ─────────────────────────────────────────────────────────────

# Chave Fernet p/ criptografar segredos por usuário em repouso (Track A4).
# Gere com: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
SECRETS_FERNET_KEY = os.getenv("SECRETS_FERNET_KEY", "")

# Sessões do Mercado Livre usam envelope encryption separado dos campos Fernet.
# JSON: {"v1":"<base64 de 32 bytes>", "v2":"..."}. A versão corrente permite
# rotacionar sem perder a leitura de blobs anteriores.
ML_SESSION_KEKS_JSON = os.getenv("ML_SESSION_KEKS_JSON", "")
if not ML_SESSION_KEKS_JSON and os.getenv("ML_SESSION_KEKS_JSON_B64"):
    import base64
    _ml_keyring_b64 = os.environ["ML_SESSION_KEKS_JSON_B64"]
    ML_SESSION_KEKS_JSON = base64.urlsafe_b64decode(
        _ml_keyring_b64 + ("=" * (-len(_ml_keyring_b64) % 4))
    ).decode("utf-8")
ML_SESSION_CURRENT_KEY_VERSION = os.getenv("ML_SESSION_CURRENT_KEY_VERSION", "v1")
ML_LEGACY_SESSION_READ_ENABLED = os.getenv(
    "ML_LEGACY_SESSION_READ_ENABLED",
    "0" if APP_ENV in {"staging", "production"} else "1",
) == "1"

# Organização cuja sessão ML alimenta a raspagem do CATÁLOGO COMPARTILHADO
# (Produto/Cupom têm owner=None; ver MIXED_TENANT_TABLES em accounts/rls.py).
# O loop de automação roda como @system_job, sem usuário — sem isto ele raspava
# anônimo e a tabela Cupom ficava vazia, o que travava a geração de link em
# link.py. Escolha explícita e auditável: nunca varremos tenants atrás de uma
# credencial. Vazio = a raspagem automática não usa sessão e avisa no log.
ML_SYSTEM_ORGANIZATION_ID = os.getenv("ML_SYSTEM_ORGANIZATION_ID", "").strip()

# ─────────────────────────────────────────────────────────────
# Cotas por usuário (default global; Perfil pode sobrescrever por usuário).
# Protegem a máquina compartilhada — um usuário não estoura o recurso comum.
# 0/vazio no Perfil = usa estes defaults.
# ─────────────────────────────────────────────────────────────
QUOTA_MAX_CONFIGS = int(os.getenv("QUOTA_MAX_CONFIGS", "20"))
QUOTA_MAX_ENVIOS_DIA = int(os.getenv("QUOTA_MAX_ENVIOS_DIA", "300"))
QUOTA_MAX_WA_SESSIONS = int(os.getenv("QUOTA_MAX_WA_SESSIONS", "1"))

# ─────────────────────────────────────────────────────────────
# Painel de infra do superadmin — métricas Fly (somente leitura).
# FLY_API_TOKEN vazio = painel mostra "indisponível" (dev). Gere com `fly auth token`.
# ─────────────────────────────────────────────────────────────
FLY_API_TOKEN = os.getenv("FLY_API_TOKEN", "")
FLY_API_HOST = os.getenv("FLY_API_HOST", "https://api.machines.dev")
FLY_APPS = [a.strip() for a in os.getenv(
    "FLY_APPS", "spreading-web,spreading-wa").split(",") if a.strip()]
# Custo mensal aproximado do conjunto compartilhado (USD) — estático, do DEPLOY.md.
FLY_CUSTO_MENSAL_USD = os.getenv("FLY_CUSTO_MENSAL_USD", "15-30")

# ─────────────────────────────────────────────────────────────
# Vigia externo do worker WhatsApp (wa_supervisor). O watchdog interno morre
# junto quando a VM congela, e o Fly não reinicia máquina por health check
# critical — alguém de fora precisa derrubá-la. Roda no POLL de 15s do processo
# `monitor`: com 6 falhas a recuperação leva ~90s. Sem FLY_API_TOKEN = no-op.
# WA_SUPERVISOR_FALHAS: sondas /health seguidas falhando antes de reiniciar.
# WA_SUPERVISOR_COOLDOWN_MIN: intervalo mínimo entre restarts (anti-loop).
# ─────────────────────────────────────────────────────────────
WA_SUPERVISOR_ENABLED = os.getenv("WA_SUPERVISOR_ENABLED", "1") == "1"
WA_SUPERVISOR_FALHAS = int(os.getenv("WA_SUPERVISOR_FALHAS", "6"))
WA_SUPERVISOR_COOLDOWN_MIN = int(os.getenv("WA_SUPERVISOR_COOLDOWN_MIN", "15"))
WA_MACHINE_APP = os.getenv("WA_MACHINE_APP", "spreading-wa")

# ─────────────────────────────────────────────────────────────
# Observabilidade: logging estruturado no console (capturado pelo honcho/Fly) +
# Sentry opcional. Os loops (scrape/envio/senders) engolem exceções com try/except;
# logar no logger 'apps' garante que apareçam nos logs (e no Sentry, se configurado).
# ─────────────────────────────────────────────────────────────
#
# APPS_LOG_LEVEL sobe para DEBUG sem redeploy (fly secrets set APPS_LOG_LEVEL=DEBUG)
# quando for preciso ver o erro card a card. Não é o default porque os scrapers logam
# uma linha por item descartado e afogariam o resto — os pontos que importam ganharam
# contadores agregados em nível INFO/WARNING (ver ofertas_scraper._logar_descartes).
_APPS_LOG_LEVEL = os.getenv("APPS_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "()": "core.logging.RedactingFormatter",
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "apps": {"handlers": ["console"], "level": _APPS_LOG_LEVEL, "propagate": False},
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}

SENTRY_DSN = os.getenv("SENTRY_DSN", "")
# A suíte exercita de propósito os caminhos de erro — sessão caída, fonte
# bloqueada, envio recusado — e cada `logger.error` desses virava evento no Sentry.
# Rodar os testes com um `.env` de desenvolvimento preenchido gastava cota e sujava
# a triagem com falhas encenadas. O DSN continua sendo lido normalmente fora do
# `manage.py test`.
RUNNING_TESTS = "test" in sys.argv[1:2] or bool(os.getenv("PYTEST_CURRENT_TEST"))
if RUNNING_TESTS:
    SENTRY_DSN = ""
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration

        sentry_logging = LoggingIntegration(
            level=logging.INFO,         # breadcrumbs a partir de INFO
            event_level=logging.ERROR,  # ERROR+ vira evento Sentry
        )
        def _sentry_before_send(event, _hint):
            """Nunca envia corpos HTTP ou credenciais acidentais ao Sentry.

            ``send_default_pii=False`` não desliga a coleta de ``request.data``.
            Isso é especialmente importante em ``/scrapers/ml/input/``, cujo corpo
            transporta as teclas do login remoto (inclusive senha e 2FA).
            """
            request = event.get("request")
            if isinstance(request, dict):
                request.pop("data", None)
                headers = request.get("headers")
                if isinstance(headers, dict):
                    for key in list(headers):
                        if key.lower() in {"authorization", "cookie", "set-cookie"}:
                            headers[key] = "[Filtered]"
            return event

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration(), sentry_logging],
            traces_sample_rate=float(os.getenv("SENTRY_TRACES_RATE", "0.0")),
            send_default_pii=False,
            max_request_body_size="never",
            before_send=_sentry_before_send,
            environment=os.getenv("SENTRY_ENV", "prod" if not DEBUG else "dev"),
            release=os.getenv("SENTRY_RELEASE") or None,
        )
    except Exception as exc:  # sentry-sdk ausente ou DSN inválido — não derruba o boot
        logging.getLogger(__name__).warning(
            "Sentry não foi inicializado (%s).", type(exc).__name__
        )
