# Generated by Django 6.0.8 on 2026-09-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0074_cache_persistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True)),
                ('modelo', models.CharField(max_length=80)),
                ('origem', models.CharField(max_length=40)),
                ('chamadas', models.PositiveIntegerField(default=0)),
                ('tokens_entrada', models.BigIntegerField(default=0)),
                ('tokens_saida', models.BigIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('competencia', 'modelo', 'origem'), name='gastoia_unico_por_mes_modelo_origem')],
            },
        ),
    ]
